version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: spring-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-auth-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring-auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
